workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Create Fresh Android Platform and Add Firebase
        script: |
          # नया एंड्रॉइड फोल्डर जनरेट करना
          flutter create . --org com.laxmitrading.app --platforms=android
          
          # सुनिश्चित करना कि गूगल सर्विसेज प्लगइन जुड़ जाए
          echo "apply plugin: 'com.google.gms.google-services'" >> android/app/build.gradle
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
