plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
}

android {
    namespace "com.laxmitrading.app"
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.laxmitrading.app"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }
}
